version: '3.9'

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  web:
    build: ./
    restart: always
    command: ["web"]
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  celery:
    restart: always
    build: .
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - redis
      - webapp
    command: ["celery"]