version: '3.9'

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  web:
    build: ./
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  celery_worker:
    build: ./
    restart: always
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - redis
      - web
    command: celery -A config worker --loglevel=info -P eventlet

  celery_beat:
    build: ./
    restart: always
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - redis
      - web
    command: celery -A config beat -l info

  celery_flower:
    build: ./
    restart: always
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - redis
      - web
    ports:
      - 5555:5555
    command: celery -A config flower --port=5555